name: Update Ensi data
on:
  workflow_dispatch:
    inputs:
      json:
        description: "Data JSON"
        required: true
        type: string

jobs:
  generate-addon:
    runs-on: ubuntu-latest
    name: "Update data"
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Set github config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Write to file
        uses: "DamianReeves/write-file-action@v1.2"
        with:
          path: src/values/ensi.json
          write-mode: overwrite
          contents: ${{ github.event.inputs.json }}
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "feat(ensi): update addon"
      - name: Push changes
        run: git push